### ISSUE TITLE
Some contacts doesn't show up

### ISSUE THREAD

**Issue by zubusoomro** [ajkh35/ContactsDemo#5]
Some contacts doesn't show the aggregated contact information. sometimes the contacts gets aggregated but they don't get updated in the contacts app upon restarting the device the contacts show up perfectly. Sometimes only a single contact gets stuck and does not show the aggregated contact whatever we do upon deleting and adding the contact again sometimes fixes the problem. If you have any suggestions i will appreciate it. Thankyou

**Comment by ajkh35** [comment]
Hi @zubusoomro, 

1.) About contacts not aggregating by itself, this might be a device specific issue where there might be custom UI like samsung uses or maybe some manufacturer customization that prevents it. It works just fine on vanilla android. So you might check for manufacturer customizations.

2.) When just a single contact doesn't get aggregated. Honestly speaking this is a first. I have known issues like contacts duplication and no contact getting aggregated but never known one contact not aggregated. Here I can suggest just check the position of the contact not aggregated and try it two three times to observe some pattern maybe regarding which contact doesn't get aggregated. This might help.

I hope these suggestions help you. Regards.
