### ISSUE TITLE
How to save this type of number in database"+913012345678"?

### ISSUE THREAD

**Issue by hamza0786** [ajkh35/ContactsDemo#9]
hey
i want to know how to save number with special characters such as"+,()$...
when i type this type of number it say enter valid number...
plz help!

**Comment by ajkh35** [comment]
Hey @hamza0786,
Just open the file MainActivity.kt and search for this string "!register_number.text.toString().matches("[0-9]+".toRegex())". Here just change the regex pattern to whatever you would like to have.
Thanks
